In [76]:
import pandas as pd
import datetime as dt


data=pd.read_csv(r"C:\Users\mohda\Documents\thesis first\3yp\lockdowns\interventions.csv")
data=pd.DataFrame(data)

data=data.fillna(1)

for i in range(3,len(data.columns)):
    x=data.iloc[:,i]
    data.iloc[:,i]=x.astype(int).apply(dt.datetime.fromordinal)

data.to_csv(r"C:\Users\mohda\Documents\thesis first\3yp\outputs\interventions.csv")

In [72]:
import datetime as dt

data=data.fillna(1)

for i in range(3,len(data.columns)):
    x=data.iloc[:,i]
    data.iloc[:,i]=x.astype(int).apply(dt.datetime.fromordinal)

In [73]:
for i in range(0,len(data.columns)):
        print(i)
data

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

,FIPS,STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,stay at home rollback,>50 gatherings rollback,>500 gatherings rollback,restaurant dine-in rollback,entertainment/gym rollback
0,0,US,united states,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00
1,1000,AL,alabama,2020-04-04 00:00:00,2020-03-20 00:00:00,2020-03-13 00:00:00,2020-03-16 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,2020-04-30 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-05-11 00:00:00,2020-05-11 00:00:00
2,1001,AL,autauga county,2020-04-04 00:00:00,2020-03-20 00:00:00,2020-03-13 00:00:00,2020-03-16 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,2020-04-30 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-05-11 00:00:00,2020-05-11 00:00:00
3,1003,AL,baldwin county,2020-04-04 00:00:00,2020-03-20 00:00:00,2020-03-13 00:00:00,2020-03-16 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,2020-04-30 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-05-11 00:00:00,2020-05-11 00:00:00
4,1005,AL,barbour county,2020-04-04 00:00:00,2020-03-20 00:00:00,2020-03-13 00:00:00,2020-03-16 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,2020-04-30 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-05-11 00:00:00,2020-05-11 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,72145,PR,"vega baja municipio, puerto rico",0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-03-16 00:00:00,2020-03-15 00:00:00,2020-03-15 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00
3269,72147,PR,"vieques municipio, puerto rico",0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-03-16 00:00:00,2020-03-15 00:00:00,2020-03-15 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00
3270,72149,PR,"villalba municipio, puerto rico",0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-03-16 00:00:00,2020-03-15 00:00:00,2020-03-15 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00
3271,72151,PR,"yabucoa municipio, puerto rico",0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-03-16 00:00:00,2020-03-15 00:00:00,2020-03-15 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00
3272,72153,PR,"yauco municipio, puerto rico",0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,2020-03-16 00:00:00,2020-03-15 00:00:00,2020-03-15 00:00:00,2020-03-16 00:00:00,2020-03-11 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00,0001-01-01 00:00:00

In [65]:
data

,FIPS,STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,stay at home rollback,>50 gatherings rollback,>500 gatherings rollback,restaurant dine-in rollback,entertainment/gym rollback
0,0,US,united states,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000,AL,alabama,737519.0,737504.0,737497.0,737500.0,737503.0,737512.0,737500.0,737495.0,737545.0,NaN,NaN,737556.0,737556.0
2,1001,AL,autauga county,737519.0,737504.0,737497.0,737500.0,737503.0,737512.0,737500.0,737495.0,737545.0,NaN,NaN,737556.0,737556.0
3,1003,AL,baldwin county,737519.0,737504.0,737497.0,737500.0,737503.0,737512.0,737500.0,737495.0,737545.0,NaN,NaN,737556.0,737556.0
4,1005,AL,barbour county,737519.0,737504.0,737497.0,737500.0,737503.0,737512.0,737500.0,737495.0,737545.0,NaN,NaN,737556.0,737556.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,72145,PR,"vega baja municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0,NaN,NaN,NaN,NaN,NaN
3269,72147,PR,"vieques municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0,NaN,NaN,NaN,NaN,NaN
3270,72149,PR,"villalba municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0,NaN,NaN,NaN,NaN,NaN
3271,72151,PR,"yabucoa municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0,NaN,NaN,NaN,NaN,NaN
3272,72153,PR,"yauco municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0,NaN,NaN,NaN,NaN,NaN